#!/bin/bash

set -euo pipefail

ROOT=$(dirname "$(readlink -f "$0")")
TEST=${1:?First argument should be a test file}
TEST_NAME=$(basename "$TEST")
FOLDER=$(mktemp -d)

trap "rm -fr $FOLDER; exit" EXIT

echo "Running test $TEST"
cat "$TEST" | ./target/debug/rloxi 1>"$FOLDER/out" 2>"$FOLDER/err"

diff "$FOLDER/out" "$TEST.out"
diff "$FOLDER/err" "$TEST.err"
